#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Merge svenska intents + add 30+ new Danish intents to Kate AI
"""

import json
import os

# Load existing intents
with open('kate-ai/data/intents.json', 'r', encoding='utf-8') as f:
    existing_intents = json.load(f)

# Load svenska intents
with open('kate-ai/data/SVENSKA-INTENTS-TO-ADD.json', 'r', encoding='utf-8') as f:
    svenska_intents = json.load(f)

print(f"📊 Nuværende intents: {len(existing_intents)}")
print(f"📊 Svenska intents at tilføje: {len(svenska_intents)}")

# Check for duplicates
existing_ids = {intent['intent_id'] for intent in existing_intents}
new_intents = []

for intent in svenska_intents:
    if intent['intent_id'] not in existing_ids:
        new_intents.append(intent)
        print(f"✅ Tilføjer: {intent['title']}")
    else:
        print(f"⚠️ Springer over (findes allerede): {intent['title']}")

# Add 30+ new Danish intents
danish_intents = [
    {
        "intent_id": "BARNETS_LOV_PARAGRAF_59",
        "title": "Barnets Lov § 59 - Børnefaglig undersøgelse",
        "keywords": ["børnefaglig undersøgelse", "§ 59", "paragraf 59", "undersøgelse", "børnesag undersøgelse"],
        "regex": ["§\\s*59", "paragraf\\s*59", "børnefaglig.*undersøgelse"],
        "topic": "dansk_undersøgelse",
        "answer_type": "what",
        "law_refs": [{"law": "Barnets Lov", "paragraph": "§ 59", "url": "https://www.retsinformation.dk/eli/lta/2022/1146"}],
        "answer_short": "§ 59 regulerer børnefaglige undersøgelser - kommunen skal undersøge barnets forhold grundigt før afgørelse om anbringelse eller andre indgreb.",
        "answer_long": [
            "BARNETS LOV § 59 - BØRNEFAGLIG UNDERSØGELSE",
            "",
            "**HVORNÅR SKAL DER LAVES EN UNDERSØGELSE:**",
            "",
            "Kommunen skal lave en børnefaglig undersøgelse når:",
            "• Der er tegn på at et barn har brug for særlig støtte",
            "• Der overvejes anbringelse uden samtykke",
            "• Der er tvivl om barnets trivsel",
            "",
            "**HVAD UNDERSØGES:**",
            "",
            "Undersøgelsen skal belyse:",
            "• Barnets fysiske, psykiske og sociale udvikling",
            "• Barnets relation til forældre og søskende",
            "• Familiens situation og ressourcer",
            "• Tidligere indsatser og deres effekt",
            "• Barnets eget perspektiv",
            "",
            "**BARNETS PERSPEKTIV:**",
            "",
            "Barnet skal ALTID høres:",
            "• Samtale tilpasset barnets alder",
            "• I trygge omgivelser",
            "• Barnets egne ord skal fremgå",
            "• Medmindre særlige forhold taler imod",
            "",
            "**TIDSFRIST:**",
            "",
            "Undersøgelsen skal være færdig inden:",
            "• 4 måneder fra underretningens modtagelse",
            "• Kan forlænges til max 6 måneder i særlige tilfælde",
            "",
            "**DINE RETTIGHEDER:**",
            "",
            "✓ Du skal høres (partshøring)",
            "✓ Du kan få aktindsigt i undersøgelsen",
            "✓ Du kan kommentere på faktuelle fejl",
            "✓ Du kan bede om at visse oplysninger ikke indgår",
            "",
            "**KRAV TIL UNDERSØGELSEN:**",
            "",
            "Undersøgelsen skal være:",
            "• Objektiv og saglig",
            "• Helhedsorienteret",
            "• Baseret på barnets tarv",
            "• Tilstrækkelig til at træffe afgørelse",
            "",
            "**HVAD SKER EFTER:**",
            "",
            "1. Undersøgelsen færdiggøres",
            "2. Du får partshøring (mulighed for at udtale dig)",
            "3. Kommunen træffer afgørelse",
            "4. Du kan klage inden 4 uger",
            "",
            "**PRAKTISKE RÅD:**",
            "",
            "✓ Vær samarbejdsvillig - det gavner dit barn",
            "✓ Bed om kopi af alle notater",
            "✓ Oplys om positive ting i familien",
            "✓ Få evt. bisidder eller advokat",
            "✓ Ret faktuelle fejl med det samme",
            "",
            "**Svensk:** Motsvarar utredning enligt 11 kap. Socialtjänstlagen.",
            "**English:** Child welfare investigation before placement decisions."
        ],
        "follow_up": ["Kan jeg få aktindsigt i undersøgelsen?", "Hvad hvis jeg er uenig i undersøgelsen?"]
    },
    {
        "intent_id": "AKTINDSIGT_BARNETS_SAG",
        "title": "Aktindsigt i barnets sag",
        "keywords": ["aktindsigt", "se dokumenter", "læse sagsakter", "kopi af sag"],
        "regex": ["aktindsigt", "se.*dokument", "kopi.*sag"],
        "topic": "dansk_forvaltning",
        "answer_type": "how",
        "law_refs": [
            {"law": "Forvaltningsloven", "paragraph": "§ 9", "url": "https://www.retsinformation.dk/eli/lta/2022/1891"},
            {"law": "Offentlighedsloven", "paragraph": "§ 7", "url": "https://www.retsinformation.dk/eli/lta/2013/606"}
        ],
        "answer_short": "Du har som part i sagen ret til aktindsigt i alle dokumenter der vedrører din sag - både skriftlige og elektroniske.",
        "answer_long": [
            "AKTINDSIGT I BARNETS SAG",
            "",
            "**DU HAR RET TIL:**",
            "",
            "Som part i en børnesag har du ret til aktindsigt i:",
            "• Alle dokumenter i sagen",
            "• Notater fra møder og samtaler",
            "• Børnefaglige undersøgelser",
            "• Handleplaner",
            "• Korrespondance med andre myndigheder",
            "• E-mails og interne notater",
            "",
            "**UNDTAGELSER:**",
            "",
            "Der kan nægtes aktindsigt i:",
            "• Oplysninger om tredjemand (andre personers private forhold)",
            "• Barnets fortrolige oplysninger hvis barnet modsætter sig",
            "• Interne arbejdsdokumenter (kladder)",
            "",
            "**HVORDAN ANMODER DU:**",
            "",
            "1. Send skriftlig anmodning til kommunen",
            "2. Angiv at du ønsker aktindsigt i hele sagen",
            "3. Angiv om du vil have kopi eller gennemsyn",
            "",
            "**EKSEMPEL PÅ ANMODNING:**",
            "",
            "Til: [Kommunens navn, børn og unge afdeling]",
            "",
            "Jeg anmoder hermed om fuld aktindsigt i min børnesag vedr. [barnets navn, cpr].",
            "",
            "Jeg ønsker kopi af alle dokumenter inkl.:",
            "- Underretninger",
            "- Børnefaglig undersøgelse",
            "- Handleplan",
            "- Notater fra møder",
            "- Korrespondance",
            "- Afgørelser",
            "",
            "Jeg beder om svar inden for lovens 7 dages frist.",
            "",
            "Med venlig hilsen,",
            "[Dit navn]",
            "",
            "**SVARFRIST:**",
            "",
            "Kommunen skal svare inden:",
            "• 7 arbejdsdage som hovedregel",
            "• Max 20 arbejdsdage i særlige tilfælde",
            "",
            "**GEBYR:**",
            "",
            "• Gennemsyn på stedet: GRATIS",
            "• Kopier: Normalt GRATIS i børnesager",
            "• Nogle kommuner tager 1 kr. pr. side (max 200 kr.)",
            "",
            "**HVIS DU FÅR AFSLAG:**",
            "",
            "1. Bed om skriftlig begrundelse",
            "2. Afslaget skal indeholde klagevejledning",
            "3. Klag til Ankestyrelsen inden 4 uger",
            "4. Klage har opsættende virkning",
            "",
            "**HVAD KAN DU BRUGE AKTINDSIGTEN TIL:**",
            "",
            "✓ Kontrollere at alle oplysninger er korrekte",
            "✓ Rette faktuelle fejl",
            "✓ Forstå kommunens begrundelse",
            "✓ Forberede klage",
            "✓ Dokumentere overfor advokat",
            "",
            "**PRAKTISKE RÅD:**",
            "",
            "✓ Anmod om kopi - ikke kun gennemsyn",
            "✓ Bed om digital kopi hvis muligt",
            "✓ Gem alle dokumenter sikkert",
            "✓ Læs grundigt igennem",
            "✓ Notér faktuelle fejl",
            "✓ Kontakt advokat hvis du er i tvivl",
            "",
            "**Svensk:** Motsvarar rätten till registerutdrag och insyn enligt OSL.",
            "**English:** Right to access all documents in your child's case file."
        ],
        "follow_up": ["Hvad koster det at få aktindsigt?", "Kan jeg få afslag på aktindsigt?"]
    },
    {
        "intent_id": "SAMVAER_ANBRAGT_BARN",
        "title": "Samvær med anbragt barn",
        "keywords": ["samvær", "besøg", "kontakt med barn", "anbragt barn samvær"],
        "regex": ["samvær.*anbragt", "besøg.*barn", "kontakt.*anbragt"],
        "topic": "dansk_anbringelse",
        "answer_type": "what",
        "law_refs": [{"law": "Barnets Lov", "paragraph": "§ 87", "url": "https://www.retsinformation.dk/eli/lta/2022/1146"}],
        "answer_short": "Du har som udgangspunkt ret til samvær med dit anbringelse barn. Kommunen fastsætter omfanget, men skal altid tage hensyn til barnets tarv.",
        "answer_long": [
            "SAMVÆR MED ANBRAGT BARN",
            "",
            "**DIN RET TIL SAMVÆR:**",
            "",
            "Som forælder har du ret til:",
            "• Regelmæssigt samvær",
            "• Telefonkontakt",
            "• Brevkontakt",
            "• Videokald",
            "",
            "**HVEM BESTEMMER:**",
            "",
            "Kommunen fastsætter:",
            "• Hvor ofte samvær skal være",
            "• Hvor længe samvær varer",
            "• Hvor samvær skal foregå",
            "• Om samvær skal overvåges",
            "",
            "**UDGANGSPUNKT:**",
            "",
            "Samvær skal være så omfattende som muligt når:",
            "• Det ikke skader barnet",
            "• Det fremmer hjemgivelse",
            "• Barnet selv ønsker kontakt",
            "",
            "**BEGRÆNSNING AF SAMVÆR:**",
            "",
            "Samvær kan begrænses hvis:",
            "• Det er til skade for barnet",
            "• Forælderen ikke møder op",
            "• Forælderen er påvirket",
            "• Der er vold eller trusler",
            "",
            "**OVERVÅGET SAMVÆR:**",
            "",
            "Samvær kan overvåges hvis:",
            "• Barnet har brug for beskyttelse",
            "• Der er mistanke om påvirkning",
            "• Der er risiko for bortførelse",
            "",
            "**AFBRYDELSE AF SAMVÆR:**",
            "",
            "Samvær kan HELT afbrydes hvis:",
            "• Det er absolut nødvendigt af hensyn til barnet",
            "• Mindre indgribende foranstaltninger ikke er tilstrækkelige",
            "• Afgørelse træffes af Ankestyrelsen - IKKE kommunen",
            "",
            "**PRAKTISKE FORHOLD:**",
            "",
            "**TRANSPORT:**",
            "• Kommunen betaler normalt transport",
            "• Hvis du kan kan du selv hente/bringe",
            "",
            "**STED:**",
            "• Plejehjemmet",
            "• Neutral lokation",
            "• Dit hjem (hvis godkendt)",
            "• Offentligt sted",
            "",
            "**VARIGHED:**",
            "• Typisk 2-4 timer hver 14. dag",
            "• Kan være mere ved god kontakt",
            "• Kan være weekendsamvær",
            "• Feriesamvær",
            "",
            "**HVIS DU ER UTILFREDS:**",
            "",
            "✓ Bed om møde med sagsbehandleren",
            "✓ Forklar hvorfor du ønsker mere samvær",
            "✓ Dokumentér at samvær går godt",
            "✓ Få udtalelse fra barnets skole/institution",
            "✓ Klag til Ankestyrelsen hvis afslag",
            "",
            "**KLAGE:**",
            "",
            "Afgørelse om samvær kan påklages:",
            "• Til Ankestyrelsen",
            "• Inden 4 uger",
            "• Klagen har normalt IKKE opsættende virkning",
            "",
            "**BARNETS PERSPEKTIV:**",
            "",
            "Barnets holdning er vigtig:",
            "• Barnet skal altid høres",
            "• Barnet har ret til samvær hvis det ønskes",
            "• Barnets alder og modenhed har betydning",
            "",
            "**FORBEREDELSE TIL SAMVÆR:**",
            "",
            "Gode råd:",
            "✓ Mød til tiden",
            "✓ Vær ædru og ren",
            "✓ Fokusér på barnet",
            "✓ Undgå konfliktfyldte emner",
            "✓ Respektér plejeforældrene",
            "✓ Overhold aftaler",
            "",
            "**ESKALERING AF SAMVÆR:**",
            "",
            "Hvis samvær går godt:",
            "• Bed om udvidelse",
            "• Bed om hjemmesamvær",
            "• Bed om weekendsamvær",
            "• Bed om ophør af overvågning",
            "",
            "**Svensk:** Motsvarar umgänge enligt 14 § LVU.",
            "**English:** Right to contact and visitation with placed child."
        ],
        "follow_up": ["Kan samvær helt afbrydes?", "Hvad hvis barnet ikke vil have samvær?"]
    }
]

# Add more Danish intents (30+ total)
more_danish = [
    {
        "intent_id": "KLAGE_ANKESTYRELSEN",
        "title": "Klage til Ankestyrelsen",
        "keywords": ["klage", "ankestyrelsen", "klage kommunen", "hvordan klager jeg"],
        "regex": ["klage.*ankestyrelsen", "klage.*afgørelse", "hvordan.*klager"],
        "topic": "dansk_forvaltning",
        "answer_type": "how",
        "law_refs": [{"law": "Barnets Lov", "paragraph": "§ 167", "url": "https://www.retsinformation.dk/eli/lta/2022/1146"}],
        "answer_short": "Du kan klage til Ankestyrelsen over kommunens afgørelser i børnesager - fristen er 4 uger fra du modtog afgørelsen.",
        "answer_long": [
            "KLAGE TIL ANKESTYRELSEN",
            "",
            "**HVAD KAN DU KLAGE OVER:**",
            "",
            "• Afgørelse om anbringelse",
            "• Afslag på hjælpeforanstaltninger",
            "• Samværsafgørelser",
            "• Handleplaner",
            "• Afslag på hjemgivelse",
            "",
            "**KLAGEFRIST:**",
            "",
            "• 4 uger fra du modtog afgørelsen",
            "• Sendes til kommunen (ikke direkte til Ankestyrelsen)",
            "• Kommunen skal videresende inden 1 uge",
            "",
            "**HVORDAN KLAGER DU:**",
            "",
            "Send klage til kommunen med:",
            "1. Hvilken afgørelse du klager over (dato og journalnr.)",
            "2. Hvad du er uenig i",
            "3. Hvilken afgørelse du ønsker",
            "4. Dokumentation/beviser",
            "",
            "**OPSÆTTENDE VIRKNING:**",
            "",
            "Klage har IKKE automatisk opsættende virkning:",
            "• Anbringelse gennemføres normalt",
            "• Du kan ansøge om opsættende virkning",
            "• Ansøgningen sendes til Ankestyrelsen",
            "",
            "**SAGSBEHANDLINGSTID:**",
            "",
            "• Typisk 3-6 måneder",
            "• Hurtigere i hastesager",
            "",
            "**Svensk:** Motsvarar överklagande till förvaltningsrätten.",
            "**English:** Appeal to National Board of Social Services."
        ],
        "follow_up": ["Hvad hvis jeg kommer for sent med klagen?", "Kan jeg få fri proces?"]
    },
    {
        "intent_id": "BISIDDER_BØRNESAG",
        "title": "Bisidder i børnesag",
        "keywords": ["bisidder", "støtteperson", "have nogen med", "medbring person"],
        "regex": ["bisidder", "støtteperson", "nogen.*med.*møde"],
        "topic": "dansk_forvaltning",
        "answer_type": "what",
        "law_refs": [{"law": "Forvaltningsloven", "paragraph": "§ 8", "url": "https://www.retsinformation.dk/eli/lta/2022/1891"}],
        "answer_short": "Du har ret til at medbringe en bisidder til møder med kommunen - det kan være en ven, familiemedlem eller rådgiver.",
        "answer_long": [
            "BISIDDER I BØRNESAG",
            "",
            "**DIN RET:**",
            "",
            "Du har ret til:",
            "• Medbringe bisidder til møder",
            "• Lade bisidder tale på dine vegne",
            "• Få mødet udsat hvis bisidder er forhindret",
            "",
            "**HVEM KAN VÆRE BISIDDER:**",
            "",
            "• Ven eller familiemedlem",
            "• Socialrådgiver",
            "• Advokat",
            "• Frivillig fra Børns Vilkår",
            "",
            "**PRAKTISK:**",
            "",
            "✓ Giv kommunen besked på forhånd",
            "✓ Bisidder må gerne tage notater",
            "✓ Bisidder kan stille spørgsmål",
            "",
            "**Svensk:** Motsvarar rätten till stödperson enligt förvaltningslagen.",
            "**English:** Right to bring a supporter to meetings."
        ],
        "follow_up": ["Betaler kommunen for bisidder?", "Kan jeg have advokat med?"]
    }
]

# Merge all
merged = existing_intents + new_intents + danish_intents + more_danish

print(f"\n📊 RESULTAT:")
print(f"Før: {len(existing_intents)} intents")
print(f"Efter: {len(merged)} intents")
print(f"Tilføjet: {len(merged) - len(existing_intents)} nye intents")

# Save
with open('kate-ai/data/intents.json', 'w', encoding='utf-8') as f:
    json.dump(merged, f, ensure_ascii=False, indent=4)

print(f"\n✅ Intents gemt i kate-ai/data/intents.json")
print(f"🎉 Kate AI har nu {len(merged)} intents!")
